HR_Project.Presentation/Controllers/ExpenseController.cs
using HR_Project.Application.Services.ExpenseService;
using AutoMapper;
using HR_Project.Application.Models.VMs;
using HR_Project.Application.Services.CurrencyService;
using HR_Project.Domain.Entities.Concrete;
using HR_Project.Domain.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using HR_Project.Application.Services.ExpenseTypeService;
using HR_Project.Application.Models.DTOs;


namespace HR_Project.Presentation.Controllers
{
    [Authorize]
    public class ExpenseController : Controller
    {
        private readonly IExpenseService _expenseService;
        private readonly IExpenseTypeService _expenseTypeService;
        private IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<Personnel> _userManager;
        private readonly ICurrencyService _currencyService;
        private readonly IMapper _mapper;

        public ExpenseController(IExpenseService expenseService, IWebHostEnvironment webHostEnvironment, UserManager<Personnel> userManager, ICurrencyService currencyService, IMapper mapper, IExpenseTypeService expenseTypeService)
        {
            _expenseService = expenseService;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
            _currencyService = currencyService;
            _mapper = mapper;
            _expenseTypeService = expenseTypeService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var expenses = await _expenseService.GetAllExpensesAsync(user.Id);

                List<ExpenseVM> listExpenseModel = new List<ExpenseVM>();
                foreach (var expense in expenses)
                {
                    ExpenseVM expenseVM = new ExpenseVM();
                    _mapper.Map(expense, expenseVM);
                    expenseVM.Currency = await _currencyService.GetCurrencyAsync(expenseVM.CurrencyCode);
                    if (expenseVM.ExpenseTypeID != null)
                        expenseVM.ExpenseType = await _expenseTypeService.GetExpenseTypeAsync(expense.ExpenseTypeID);
                    listExpenseModel.Add(expenseVM);
                }
                return View(listExpenseModel);
            }
            catch (Exception ex)
            {
                //_logger.LogError(ex, "Hata oluştu: {Message}", ex.Message);
                // Hata günlüğüne kayıt atılır, ayrıca kullanıcıya bir hata sayfası gösterilebilir
                //return RedirectToAction("Error"); // Örnek bir hata sayfasına yönlendirme
                return View();
            }
        }


        [HttpGet]
        public async Task<IActionResult> CreateExpenseRequest()
        {
            var model = new CreateExpenseDTO();

            model.CurrencyCodeOptions = await _currencyService.GetAllCurrenciesAsync();
            model.ExpenseTypes = await _expenseTypeService.GetAllExpenseTypesAsync();

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> CreateExpenseRequest(CreateExpenseDTO expense, IFormFile documentFile)
        {
            if (User.Identity.IsAuthenticated)
            {
                var personnelId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                if (!string.IsNullOrEmpty(personnelId))
                {
                    expense.PersonnelID = int.Parse(personnelId);
                }
            }

            if (documentFile != null && documentFile.Length > 0)
            {
                var uniqueFileName = Guid.NewGuid().ToString() + "_" + documentFile.FileName;
                var filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await documentFile.CopyToAsync(stream);
                }

                expense.DocumentPath = uniqueFileName;
            }


            var selectedExpenseType = await _expenseTypeService.GetExpenseTypeAsync(expense.ExpenseTypeID);

            if (selectedExpenseType != null && (expense.Amount < selectedExpenseType.MinAmount || expense.Amount > selectedExpenseType.MaxAmount))
            {
                ModelState.AddModelError("Amount", $"The Amount must be between {selectedExpenseType.MinAmount} and {selectedExpenseType.MaxAmount}.");
                expense.CurrencyCodeOptions = await _currencyService.GetAllCurrenciesAsync();
                expense.ExpenseTypes = await _expenseTypeService.GetAllExpenseTypesAsync();

                return View(expense);
            }


            await _expenseService.CreateExpenseRequestAsync(expense);

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> GetByFilteredExpense(ApprovalStatus approvalStatus)
        {
            var user = await _userManager.GetUserAsync(User);
            var expenses = await _expenseService.GetFilteredExpenseAsync(user.Id, approvalStatus);
            List<ExpenseVM> listExpenseModel = new List<ExpenseVM>();
            foreach (var expense in expenses)
            {
                ExpenseVM expenseVM = new ExpenseVM();
                _mapper.Map(expense, expenseVM);
                expenseVM.Currency = await _currencyService.GetCurrencyAsync(expense.CurrencyCode);
                //expenseVM.ExpenseType = await _expenseTypeService.GetExpenseTypeAsync(expense.ExpenseTypeID);
                listExpenseModel.Add(expenseVM);
            }
            return View(listExpenseModel);
        }


        public async Task<IActionResult> GetExpenseDocument(int id)
        {
            var expense = await _expenseService.GetExpenseAsync(id);

            if (expense == null)
            {
                return NotFound();
            }
            //string filePath = expense.DocumentPath;
            //Projedeki Dosya yolu
            string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", expense.DocumentPath);
            //string filePath = Path.Combine("~/images", expense.DocumentPath);

            //string filePath = "C://Users//gulde//source//repos//HR_Project//HR_Project//HR_Project.Presentation//wwwroot//images//f0190444-4e81-4219-9d8b-50f1453528ca_1.jpg";
            //string filePath = "C:/Users/gulde/source/repos/HR_Project/HR_Project/HR_Project.Presentation/wwwroot/images/f0190444-4e81-4219-9d8b-50f1453528ca_1.jpg";
            //string filePath = "C:\\Users\\gulde\\source\\repos\\HR_Project\\HR_Project\\HR_Project.Presentation\\wwwroot\\images\\f0190444-4e81-4219-9d8b-50f1453528ca_1.jpg";


            if (!System.IO.File.Exists(filePath))
            {
                // Dosya yoksa hata ver veya başka bir işlem yap
                return NotFound();
            }


            // Dosyayı döndürün.
            //return PhysicalFile(filePath, "application/octet-stream");

            // Dosyayı döndürmek için File metodunu kullanın
            // "application/pdf" gibi doğru MIME türünü belirtmelisiniz
            //return File(filePath, "application/pdf", "dosya_adi.pdf");


            string mimeType = "image/jpg";
            //return File(filePath, "image/png", "dosya_adi.png");

            // Dosyayı döndürmek için File metodunu kullanın
           // return File(filePath, mimeType, expense.DocumentPath);

            return View(expense);
        }

        public async Task<IActionResult> DeleteExpense(int id)
        {
            await _expenseService.RemoveExpense(id);
            return View("Index");
        }

    }

}

HR_Project.Presentation/Views/Expense/CreateExpenseRequest.cshtml
@using HR_Project.Application.Models.DTOs;
@model CreateExpenseDTO


<div class="content-wrapper">
    <div class="row" style="height: 50px;">
    </div>

    <div class="row">
        
        <div class="col-12 grid-margin">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title" style="text-align:center">Request Expense</h4>
                    <form class="form-sample" asp-action="CreateExpenseRequest" method="post" enctype="multipart/form-data">
                        <br />
                        <br />
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label" asp-for="Amount">Amount</label>
                                    <div class="col-sm-9">
                                        <input type="number" class="form-control" asp-for="Amount" />
                                        <span asp-validation-for="Amount" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label" asp-for="CurrencyCode">Currency Code</label>
                                    <div class="col-sm-9">
                                        <select class="form-control" asp-for="CurrencyCode">
                                            <option value="">Select Currency</option>
                                            @foreach (var currency in Model.CurrencyCodeOptions)
                                            {
                                                <option value="@currency.Code">@currency.Code</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label" asp-for="ExpenseTypeID">Expense Type</label>
                                    <div class="col-sm-9">
                                        <select class="form-control" asp-for="ExpenseTypeID">
                                            <option value="">Select Expense Type</option>
                                            @foreach (var expenseType in Model.ExpenseTypes)
                                            {
                                                <option value="@expenseType.ID">@expenseType.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label" asp-for="DocumentPath">Document</label>
                                    <div class="col-sm-9">
                                        <input asp-for="DocumentPath" type="file" class="form-control" name="documentFile" accept=".png, .pdf, .jpg, .jpeg" />
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        <br /><br />
                        <div class="form-group">
                            <button type="submit" class="btn btn-success" style="width:200px;height:30px">Create</button>
                        </div>
                        <br />
                        <div>
                            <a class="btn btn-success ml-auto " href="/Home/Index"> Go Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
	}

HR_Project.Presentation/Views/Expense/GetByFilteredExpense.cshtml
@using HR_Project.Application.Models.VMs;
@using HR_Project.Domain.Enums;
@model List<ExpenseVM>
<br />
<br />
<br />
<br />
<br />
<div class="container">
<h3 class="gradienttext">Filtered Expense List</h3>
<table class="table table-bordered table-striped table-light">
    <thead>
        <tr>
            <th>Amount</th>
            <th>Approval Status</th>
            <th>Request Date</th>
            <th>Reply Date</th>
            @*<th>Expense Type</th>*@
            <th>Currency</th>
            <th>Document Path</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Amount</td>
                <td>@item.ApprovalStatus</td>
                <td>@item.RequestDate</td>
                <td>@item.ReplyDate</td>
                @*<td>@item.ExpenseType.Name</td>*@
                <td>@item.Currency.Name</td>
                <td>@item.DocumentPath</td>
            </tr>
        }
    </tbody>
</table>
    <a class="btn btn-success ml-auto " href="/Expense/Index"> Go Back</a>
</div>

HR_Project.Presentation/Views/Expense/GetExpenseDocument.cshtml
@using HR_Project.Domain.Entities.Concrete;
@model Expense
<br />
<div class="left-container" style="width: 100%;height:100%">
	@if (@Model.DocumentPath.Contains(".pdf"))
	{
		<iframe src="~/images/@Model.DocumentPath" style="width: 100%; height: 100%;"></iframe>

	}
	else
	{
		<img src="~/images/@Model.DocumentPath" alt="Profile Image" id="profile-image">
	}

</div>

HR_Project.Presentation/Views/Expense/Index.cshtml
@using HR_Project.Application.Models.VMs;
@using HR_Project.Domain.Enums;
@model List<ExpenseVM>

<div class="content-wrapper">
    <div class="row" style="height: 50px;"></div>
    <div class="row">
        <div class="col-12 grid-margin">
            <div class="card">
                <div class="card-body">
                    <ul class="nav nav-tabs" id="myTabs">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#pendingRequests">Pending Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#acceptedRequests">Accepted Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#rejectedRequests">Rejected Requests</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div id="pendingRequests" class="tab-pane fade show active">
                            <!-- Bekleyen İstekler Tablosu Burada -->
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            @*<th>ID</th>*@
                                            <th>Expense Type</th>
                                            <th>Amount</th>
                                            <th>Currency</th>
                                            <th>Request Date</th>
                                            <th>Reply Date</th>
                                            <th>Approval Status</th>
                                            <th>Document</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            if (item.ApprovalStatus == ApprovalStatus.Pending)
                                            {
                                                <tr style="background-color:white">
                                                    @*<td>@item.ID</td>*@
                                                    <td>@item.ExpenseType.Name</td>
                                                    <td>@item.Amount</td>
                                                    <td>@item.Currency.Name</td>
                                                    <td>@item.RequestDate</td>
                                                    <td>@item.ReplyDate</td>
                                                    <td>@item.ApprovalStatus</td>
                                                    <td>
                                                        @item.DocumentPath
                                                        <br />
                                                        <a asp-route-id="@item.ID" asp-controller="Expense" asp-action="GetExpenseDocument" class="btn btn-primary" target="_blank">Show Document</a>
                                                    </td>
                                                   
                                                    <td><a asp-route-id="@item.ID" class="btn btn-danger mdi mdi-delete" asp-action="DeleteExpense" onclick="return confirm('Are you sure you want to delete?')"></a></td>
                                                </tr>
                                            }

                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div id="acceptedRequests" class="tab-pane fade">
                            <!-- Kabul Edilen İstekler Tablosu Burada -->
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            @*<th>ID</th>*@
                                            <th>Expense Type</th>
                                            <th>Amount</th>
                                            <th>Currency</th>
                                            <th>Request Date</th>
                                            <th>Reply Date</th>
                                            <th>Approval Status</th>
                                            <th>Document</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            if (item.ApprovalStatus == ApprovalStatus.Approved)
                                            {
                                                <tr>
                                                    @*<td>@item.ID</td>*@
                                                    <td>@item.ExpenseType.Name</td>
                                                    <td>@item.Amount</td>
                                                    <td>@item.Currency.Name</td>
                                                    <td>@item.RequestDate</td>
                                                    <td>@item.ReplyDate</td>
                                                    <td>@item.ApprovalStatus</td>
                                                    <td>
                                                        @item.DocumentPath
                                                        <br />
                                                        <a asp-route-id="@item.ID" asp-controller="Expense" asp-action="GetExpenseDocument" class="btn btn-primary" target="_blank">Show Document</a>
                                                    </td>
                                                    
                                                    <td>@*<a asp-route-id="@item.ID" asp-controller="Expense" asp-action="DeleteExpense" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete?')">Cancel</a>*@</td>
                                                </tr>
                                            }

                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div id="rejectedRequests" class="tab-pane fade">
                            <!-- Reddedilen İstekler Tablosu Burada -->
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            @*<th>ID</th>*@
                                            <th>Expense Type</th>
                                            <th>Amount</th>
                                            <th>Currency</th>
                                            <th>Request Date</th>
                                            <th>Reply Date</th>
                                            <th>Approval Status</th>
                                            <th>Document</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            if (item.ApprovalStatus == ApprovalStatus.Rejected)
                                            {
                                                <tr>
                                                    @*<td>@item.ID</td>*@
                                                    <td>@item.ExpenseType.Name</td>
                                                    <td>@item.Amount</td>
                                                    <td>@item.Currency.Name</td>
                                                    <td>@item.RequestDate</td>
                                                    <td>@item.ReplyDate</td>
                                                    <td>@item.ApprovalStatus</td>
                                                    <td>
                                                        @item.DocumentPath
                                                        <br />
                                                        <a asp-route-id="@item.ID" asp-controller="Expense" asp-action="GetExpenseDocument" class="btn btn-primary" target="_blank">Show Document</a>
                                                    </td>
                                                    
                                                    <td>@*<a asp-route-id="@item.ID" asp-controller="Expense" asp-action="DeleteExpense" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete?')">Cancel</a>*@</td>
                                                </tr>
                                            }

                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <a class="btn btn-success ml-auto " href="/Home/Index"> Go Back</a>
                </div>
            </div>
        </div>
    </div>
</div>